### ISSUE TITLE
In OHIF example, why two orthancs?

### ISSUE THREAD

**Issue by dscarmo** [orthanc-server/orthanc-setup-samples#6]
Hello, on the example in this repository for ohif integration in https://github.com/orthanc-server/orthanc-setup-samples/tree/master/docker/ohif, there is a orthanc-plugin and orthanc-container. 

Here is the .yml itself: https://github.com/orthanc-server/orthanc-setup-samples/blob/master/docker/ohif/docker-compose.yml

I was able to run this setup with only one orthanc service, after merging both configurations into one.

I am afraid I might have misunderstood and am missing something. Are the two Orthanc instances necessary in that example?

Thank you in advance

**Comment by amazy** [comment]
Hi @dscarmo 

No, the 2 services are there to demonstrate the 2 possible configurations (plugins or container) but, in production, you should only use one of these configuration.

**Comment by dscarmo** [comment]
Thank you!
