### ISSUE TITLE
Example for Orthanc-Explorer-2 is missing

### ISSUE THREAD

**Issue by gdevenyi** [orthanc-server/orthanc-setup-samples#7]
This line on https://github.com/orthanc-server/orthanc-setup-samples

[Use Orthanc-Explorer-2](https://github.com/orthanc-server/orthanc-setup-samples/blob/master/docker/orthanc-explorer-2) to demonstrate how to use Orthanc-Explorer-2 with an admin and a standard user interface.

is 404

**Comment by jodogne** [comment]
Thanks for the report: This is now fixed.
