### ISSUE TITLE
We want Orthan server to support Ubuntu server without docker

### ISSUE THREAD

**Issue by TomHsiung** [orthanc-server/orthanc-setup-samples#8]
Dear, sir or madam

We found that the OHIF Viewer requires a DICOM server to work. The OHIF developers recommend some DICOM server, one of which is Orthan. However, the guide here requires docker before the setup of Orthan server. Therefore, we wonder if we can bypass docker and install Orthan sever directly on a Ubuntu server.

Many thanks.

Regards,

Tom

**Comment by jodogne** [comment]
Hello,

Yes, it is evidently possible to install Orthanc on Ubuntu without Docker. [Check out the documentation](https://orthanc.uclouvain.be/book/users/cookbook.html#obtaining-binaries).

Regards,
Sébastien-
