### ISSUE TITLE
I want to enable webhooks in Orthanc. How can I do that? Does Orthanc support webhooks?

### ISSUE THREAD

**Issue by viniith21** [orthanc-server/orthanc-setup-samples#9]

**Comment by amazy** [comment]
Please use https://discourse.orthanc-server.org/ for this kind of questions

**Comment by viniith21** [comment]
> Please use https://discourse.orthanc-server.org/ for this kind of questions

Actually when i am trying to create account it it is not allowing me it is showing email already registered and also for the Activation code which i dont have then on  error it is showing me please use Forgot password and on use of Forgot password it is showing me No account matches 

how can i ask my dobut on that forum then

**Comment by jodogne** [comment]
> how can i ask my dobut on that forum then

Maybe by contacting people by e-mail? https://discourse.orthanc-server.org/t/new-users-only-accepted-on-invitation-because-of-spammers/5093/2

**Comment by viniith21** [comment]
@jodogne Hey buddy, I need some help. Can you please tell me why I’m facing a CORS issue with the DELETE API of Orthanc? I’m using Nginx, and I've defined the DELETE method, but I’m still encountering a CORS issue. Here’s my Ngnix configuration:
```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen  8050;

        location /orthanc/ {
            proxy_pass http://localhost:8042;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            rewrite /orthanc(.*) $1 break;

            # Allow CORS
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

            # Preflight CORS check
            if ($request_method = OPTIONS ) {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS,DELETE';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
                return 204;
            }
           
        }
    }
}

````
I would really appreciate any help or solutions you can provide!

**Comment by jodogne** [comment]
@viniith21, check out the answer above: "Please use https://discourse.orthanc-server.org/ for this kind of questions"
